
name: broker_server_1

network:
    hostname: http://localhost
    port: 6801

bootstrapServersByHostname:
- http://localhost:6801
_ http://localhost:6802

cluster:
    name: devCluster

path:
    data: ${QUE_PATH_DATA}
    log: ${QUE_PATH_LOG}