# name of the broker (human readability)
name = "broker_server_1"

bootstrapServers = [ 
    "http://localhost:6801", 
    "http://localhost:6802" 
]

[network]
hostname = "http://localhost"
port = 6801

[cluster]
name = "devCluster"

[path]
data = "${HOME}/data"
log = "${HOME}/log"